#include<stdio.h>
#include<stdlib.h>
#include<omp.h>
#include<time.h>

void write_pbm_image(void *image,int size,const char *image_name){

/*Function for writing an image,given as size x size a matrix of 0s and 1s, in a pbm file
 * image        : a pointer to the memory region that contains the image
 * size         : size of the image
 * image_name   : the name of the file to be written
 */

  FILE* image_file; 
  image_file = fopen(image_name, "w"); 

  fprintf(image_file, "P4\n# generated by\n# Alessandro Cesa\n%d %d\n%d\n", size, size, 1);

  fwrite( image, 1, size*size, image_file); 

  fclose(image_file); 
  return ;
}

void initialize(int size,char* name){
    char *grid = (char *)malloc(size*size * sizeof(char) );
   srand(time(NULL) );
#pragma omp parallel 
   {
#pragma omp  for schedule(static,100)
    for (int i=0;i<size*size;i++){
        grid[i]=(char)(rand()%2);
     }
}
    printf("writing image to %s\n", name);
    write_pbm_image((void *) grid, size, name);
    free(grid);

}

int main(int argc,char** argv){

    initialize(100,"test_random.pbm");
    return 0;
    
}
