#include<stdio.h>
#include<stdlib.h>

#include "image_handling.h"

void write_pbm_image(void *image,int size,const char *image_name){

/*Function for writing an image,given as size x size a matrix of 0s and 1s, in a pbm file
 * image        : a pointer to the memory region that contains the image
 * size         : size of the image
 * image_name   : the name of the file to be written
 */

  FILE* image_file;
  image_file = fopen(image_name, "w");

  fprintf(image_file, "P5\n# generated by\n# Alessandro Cesa\n%d %d\n%d\n", size, size, 1);

  fwrite( image, 1, size*size, image_file);

  fclose(image_file);
  return ;
}

